### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by ralphlange** [bkuner/opcUaUnifiedAutomation#18]
A recent change in the `README` file shows two more releases, R0-9 and R0-9-1, but there are no matching tags/releases in the repository.

Please always use tags for released versions, else it is impossible to track which changes went into which release.

**Comment by bkuner** [comment]
May be I don't understand the problem - and the git. In my local gitk it shows these tags.

**Comment by ralphlange** [comment]
You did not push the tags to GitHub, then.

**Comment by ralphlange** [comment]
Ping...

FWIW: the CLI command to make git push tags: `git push --tags`
