### ISSUE TITLE
Inappropriate use of signal handler for SIGINT

### ISSUE THREAD

**Issue by ralphlange** [bkuner/opcUaUnifiedAutomation#33]
The Driver Support library (in `drvOpcuaSetup()`, file `drvOpcUa.cpp` line 1098) installs a signal handler for the `SIGINT` signal that calls `exit(1)`.

This is bad for a number of reasons:
* Signal handling should be done at the application level, rather than inside a library.
* In EPICS context, `epicsExit()` should be used instead of `exit()` to make sure the EPICS shutdown hooks are being run appropriately.
* The signal commonly used to inform a process of an immanent shutdown is `SIGTERM`, not `SIGINT`.
* The POSIX `signal()` call is not recommended for installing signal handlers, according to the `signal(2)` manpage.

**Comment by bkuner** [comment]
Removed
