### ISSUE TITLE
Wrong OPC data types in OpcUaWriteItems

### ISSUE THREAD

**Issue by mbruker** [bkuner/opcUaUnifiedAutomation#36]
An ao record connected to an OPC variable with type OpcUaType_Float (not Double) will try to send WriteRequests with type Double to the server, causing the write to fail with a BadTypeMismatch error (without the error being displayed in spite of full debugging mode, which may be something worth changing). As far as I understand the type-strictness of OPC UA, this error is expected behaviour.

Editing drvOpcUa.cpp so that line 1032 reads

    case epicsFloat64T: tempValue.setFloat(*((epicsFloat64*)(uaItem)->pRecVal));break;

rather than `tempValue.setDouble` seems to solve the problem, at least for floats. I haven't checked the behaviour for fields of other types yet, though. Is there an intention behind the way it is programmed now or is it a plain bug?

**Comment by bkuner** [comment]
Ok, I had a look on it and congratulations: You found a big fat bug! All this conversion stuff doesn't work correctly.
Epics records come with the data types INT32, UINT32 and DOUBLE, so all conversions to to OPC lower data types Byte, INT16 etc will fail!
How to deal with that? 
E.g an bo records RVAL field is UINT32 but the value 0 or 1, an mbbo has the range 0..15 (suppose no special raw conversion, shifting etc), so it is not reasonable to prohibit a conversion to byte. 

Now I will just cast down with data loss and leave it to the user to read the manual and provide for correct data.

Another approach could be range checking at runtime and warn for data loss - maybe in future.
